import fellowshipSession from './fellowshipSession'
import announcement from './announcement'
import event from './event'
import ministry from './ministry'
import contactMessage from './contactMessage'
import sessionRecording from './sessionRecording'
import footer from './footer'
import contactPage from './contactPage'
import pastSermon from './pastSermon'
import podcast from './podcast'
import givingPage from './givingPage'
import program from './program'
import registration from './registration'
import aboutPage from './aboutPage'

export const schemaTypes = [fellowshipSession, announcement, event, ministry, contactMessage, sessionRecording, footer, contactPage, pastSermon, podcast, givingPage, program, registration, aboutPage]
